CLIENT_ID='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
NONCE='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
STATE='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
NRP='XXX'
PASSWORD='XXX'
DEFAULT_PENILAIAN=3

# possibly have to be dynamic tergantung semester
TAHUN_AJARAN='2024'
SEMESTER_TERM='1'